resources:
- '@type': type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig
  name: waf
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.filters.http.waf.v3.WAF
    signatures:
    - category:
        sqli:
          subcategory: statement_injection
      certainity: 5
      id: 1
      msg: dangerous query
      name: '1'
      operand: dangerousquery
      severity: 5
    - category:
        sqli:
          subcategory: statement_injection
      certainity: 5
      id: 2
      msg: hacker query
      name: '2'
      operand: ahackerwashere
      severity: 5
version_info: '0'
